### ISSUE TITLE
Hala çok eksik var.

### ISSUE THREAD

**Issue by onurravli** [onurravli/Git-Turkce-Kullanma-Kilavuzu#1]
Yazı yazarak pek anlaşılır olmuyor. En kısa sürede bir de **video** çekilmesi lazım.

**Comment by kahilkubilay** [comment]
Yazı ile daha iyi anlaşılır. Devam

**Comment by onurravli** [comment]
> Yazı ile daha iyi anlaşılır. Devam

git komutları falan yazıyla anlaşılıyor da işin içine github da girince görsel bir şeyler olması şart gibi. olmadı ekran görüntüsü koyarım.
