### ISSUE TITLE
Details are missing

### ISSUE THREAD

**Issue by kahilkubilay** [onurravli/Git-Turkce-Kullanma-Kilavuzu#2]
Repo'nun kılavuz olarak nitelendirilebilmesi için çok daha fazla detaya gereksinim var.  Aşağıdaki ayrıntılar eklenebilir veya örnek olabilir:

- Git kullanımı sırasında örnek senaryolar eklenebilir
- Bazı standart hataların (etc. conflicts) çözümlerine yer verilebilir

**Comment by onurravli** [comment]
Merhaba,

Evet size kesinlikle katılıyorum, en son 2 ay önce güncelleme yaptım dolayısıyla çok yer eksik kaldı. Şu an okuldan dolayı pek ekleme yapamıyorum ama PR'ler memnuniyetle kabul edilir. :-)

**Comment by onurravli** [comment]
Güncellemeleri ekleyeceğim. Issue için teşekkürler.
